name: CI

on:
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        label:
          - el8
        include:
          - label: el8
            container: centos:8
            install-dependency: dnf install -y python3 which
    
        container:
          - centos:centos8
    
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: dnf install -y python3 which
      - name: Coral Build
        run: ./coral build --debug=True

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: artifacts-${{ matrix.label }}
          path: ./coral-*
      - name: Upload logs
        uses: actions/upload-artifact@master
        if: ${{ always() }}  # Upload logs regardless of whether the build failed or not
        with:
          name: logs-${{ matrix.label }}
          path: ./coral_build_*/*.log
